### ISSUE TITLE
error at start, just logged in. default lang-eng.json

### ISSUE THREAD

**Issue by karthiceaswar** [AlexanderBaransky/PilotTelegramBot#8]
2021-09-21 17:31:53.534 | INFO     | init:<module>:22 - Welcome to PilotTelegramBot!
2021-09-21 17:31:53.534 | INFO     | init:<module>:23 - Starting init...
2021-09-21 17:31:53.534 | INFO     | init:<module>:27 - Normal init
2021-09-21 17:31:53.554 | INFO     | init:<module>:49 - AIOgram init                   [ OK ]
2021-09-21 17:31:53.554 | INFO     | init:<module>:50 - Jumping to Telethon init...
2021-09-21 17:31:54.422 | INFO     | modules.telethon.init:<module>:19 - Telethon init                   [ OK ]
2021-09-21 17:31:54.455 | INFO     | init:<module>:142 - SQL Alchemy init               [ OK ]
2021-09-21 17:31:54.455 | INFO     | utils.translation:__init__:16 - Available translations: eng rus ua
Traceback (most recent call last):
  File "E:\Bot\PilotTelegramBot-aiogram\PilotTelegramBot-aiogram\main.py", line 2, in <module>
    from init import dp, sched
  File "E:\Bot\PilotTelegramBot-aiogram\PilotTelegramBot-aiogram\init.py", line 144, in <module>
    tw = TranslationWorker(session, Chats, config.default_lang)
  File "E:\Bot\PilotTelegramBot-aiogram\PilotTelegramBot-aiogram\utils\translation.py", line 21, in __init__
    self.translations[i.split('.')[0]] = json.load(file)
  File "C:\Program Files\Python39\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Program Files\Python39\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 19: character maps to <undefined>

Process finished with exit code 1

**Comment by SanyaPilot** [comment]
Bot is completely untested on Windows, sorry for that.
Project now is semi-dead, wanna rewrite it later from zero because of bad quality of code
