### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 20: character maps to <undefined>

### ISSUE THREAD

**Issue by mhmdrzkii** [AlexanderBaransky/PilotTelegramBot#9]
sir i tried it and error like :

Traceback (most recent call last):
  File "c:\Users\rizkirdp\PilotTelegramBot\main.py", line 2, in <module>
    from init import dp, sched
  File "c:\Users\rizkirdp\PilotTelegramBot\init.py", line 144, in <module>
    tw = TranslationWorker(session, Chats, config.default_lang)
  File "c:\Users\rizkirdp\PilotTelegramBot\utils\translation.py", line 21, in __init__
    self.translations[i.split('.')[0]] = json.load(file)
  File "C:\Users\rizkirdp\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\rizkirdp\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 20: character maps to <undefined>

 how to fix?

**Comment by SanyaPilot** [comment]
Sorry, project is abandoned, if you really want to try it, run it on Linux distro

**Comment by mhmdrzkii** [comment]
can it be via linux?

**Comment by SanyaPilot** [comment]
No, it works nice on Linux

**Comment by mhmdrzkii** [comment]
how to use from linux? is it the same as running in cmd?

**Comment by SanyaPilot** [comment]
All instructions described in README.md

**Comment by mhmdrzkii** [comment]
do you have any videos related to bot pilot installation?

thankyou

**Comment by SanyaPilot** [comment]
No
